// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADT38gPNBR_1IjV1nt2tK8V4e1lZAiqRk',
    appId: '1:729243564178:web:c90496f415a146b5b50e4b',
    messagingSenderId: '729243564178',
    projectId: 'aovipos',
    authDomain: 'aovipos.firebaseapp.com',
    storageBucket: 'aovipos.appspot.com',
    measurementId: 'G-CKPNJZPH2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJaMK21vtdaRLMoFU56Lfl9wLyH1cp54',
    appId: '1:729243564178:android:845bad81702645ecb50e4b',
    messagingSenderId: '729243564178',
    projectId: 'aovipos',
    storageBucket: 'aovipos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UER0JXSxm04mP-l66BR1NLS6xmYcuQI',
    appId: '1:729243564178:ios:641df08bee5d7871b50e4b',
    messagingSenderId: '729243564178',
    projectId: 'aovipos',
    storageBucket: 'aovipos.appspot.com',
    androidClientId: '729243564178-d4autvjs7d0sapau80u0cd89rj44ivh6.apps.googleusercontent.com',
    iosClientId: '729243564178-lpnt9v90k4qea36vmon20a4ls9aehqga.apps.googleusercontent.com',
    iosBundleId: 'com.example.posq',
  );
}
